name: Vobo Build Feature
on: 
  push: 
    branches: 
      - feat/*

  # Allows for running manually from Actions tab
  workflow_dispatch:

# Customize the CMake build type here
env: 
  BUILD_TYPE: Debug

jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Vobo feature based on the event '${{github.event_name}}'"
      - run: echo "Building feature branch '${{github.ref}}'"
