name: Vobo Build Feature
on: 
  push: 
    branches: 
      - feat/*

  # Allows for running manually from Actions tab
  workflow_dispatch:

# Customize the CMake build type here
env: 
  BUILD_TYPE: Debug

jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v2.3.1
      - name: Workflow Trigger
        run: echo "Building Vobo feature based on the event '${{github.event_name}}'"
             echo "Building feature branch '${{github.ref}}'"
      - run: ls -la
      - run: mkdir build && cd build && cmake ..
