name: Vobo Build Main
on: 
  push: 
    branches: 
      -main

  pull_request:
    branches:
      -main

  # Allows for running manually from Actions tab
  workflow_dispatch:

# Customize the CMake build type here
env: 
  BUILD_TYPE: Debug

jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Vobo based on the event '${{github.event_name}}'"
      - run: echo "Running off of branch '${{github.ref}}'"
